---
dependencies:
  auto_size_text: ^3.0.0-nullsafety.0
  cupertino_icons: ^1.0.3
  facebook_audience_network: ^1.0.0-nullsafety.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_styled_toast: ^2.0.0
  get: ^4.1.4
  path: ^1.8.0
  share: ^2.0.4
  sqflite: ^2.0.0+4
  url_launcher: ^6.0.10
description: All Networks Packages Codes and Info
dev_dependencies:
  flutter_native_splash: ^1.2.3
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.12.0<3.0.0'
flutter:
  assets:
    - assets/google_fonts/
    - assets/sims.db
    - assets/images/
  fonts:
    - family: OpenSans_Reg
      fonts:
        - asset: assets\google_fonts\OpenSans-Regular.ttf
          weight: 700
    - family: OpenSans_Bold
      fonts:
        - asset: assets\google_fonts\OpenSans-Bold.ttf
          weight: 800
  uses-material-design: true
flutter_icons:
  android: launcher_icon
  image_path: assets/images/logo.png
  ios: false
name: simackges
version: 1.0.4+5