---
dependencies:
  cupertino_icons: ^1.0.3
  sqflite: ^2.0.0+3
  google_fonts: ^2.1.0
  share: ^2.0.1
  path: ^1.8.0
  flutter_styled_toast: ^2.0.0
  url_launcher: ^6.0.3
  auto_size_text: ^3.0.0-nullsafety.0
  get: ^4.1.4
  flutter_launcher_icons: ^0.9.0
  facebook_audience_network: ^0.9.0
  flutter:
    sdk: flutter
description: All Sim Packages Codes
dev_dependencies:
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.12.0-133.7.beta <3.0.0"
flutter:
  assets:
    - assets/sims.db
    - assets/images/
  uses-material-design: true
flutter_icons:
  android: launcher_icon
  image_path: assets/images/logo.png
  ios: true
name: simackges
version: 1.0.1+2
